const assortmentTextGreen = '<p>Van elektrotechnische installatiematerialen tot Verlichting, van datacommunicatie tot beveiliging: Technische Unie heeft het in huis. Ons assortiment elektrotechniek is zeer groot. Ook voor industriële toepassing leveren wij een brede range aan producten en fabricaten.<p><strong>Ons assortiment elektrotechniek</strong></p><p>Ons aanbod elektrotechniek vindt u overzichtelijk weergegeven op onze website. U vindt bij ons een ruime keuze aan:</p><ul><li>Installatiematerialen</li><li>Datacommunicatie & beveiliging</li><li>Verlichting</li><li>industriële elektrotechniek</li><li>Draad, kabel & kabeldraagystemen</li></ul><p>In onze webshop kunt u bovendien zoeken op afbeeldingen of uw zoekopdracht met zoekfilters verfijnen.</p><p><strong>Persoonlijk advies</strong></p><p>Heeft u vragen over onze producten en diensten op het gebied van elektrotechniek? Neem dan contact op met het verkoopkantoor. Onze E-specialisten staan voor u klaar met een professioneel advies. Zij adviseren u ook graag over energiezuinige toepassingen.</P>';
const assortmentTextRed = '<p>Of u nu een designradiator zoekt of een circulatiepomp, een convector of een CV-ketel; Technische Unie heeft het. Wij leveren een compleet assortiment producten voor verwarming en klimaattechniek. Van functioneel tot design en van woningbouw tot utiliteit, voor elke situatie hebben wij het juiste product. Zelfs voor zonnepanelen kunt u bij ons terecht.</p><p><strong>Een overzichtelijk aanbod</strong><br/>Binnen ons assortiment verwarming en klimaattechniek vindt producten voor:</p><ul><li>Het opwekken van warmte, zoals CV-ketels, boilers, geisers en zonnepanelen</li><li>Het afgeven van warmte, zoals radiatoren, convectoren en vloerverwarming</li><li>Het verplaatsen van warmte, zoals een rookgasafvoer of circulatiepompen</li><li>Alle installatiematerialen en onderdelen die u nodig heeft voor montage</li></ul> <p>In onze webshop kunt u bovendien zoeken op afbeeldingen of uw zoekopdracht met zoekfilters verfijnen. En heeft u vragen? Dan kunt u contact opnemen met één van de klimaatspecialisten van uw verkoopkantoor.</p><p><strong>Energie besparen</strong><br/>\'Duurzaamheid\' is een belangrijk thema, met name in de verwarming en klimaattechniek. De vraag naar duurzame, energiezuinige producten en oplossingen groeit snel.<p><p>In onze webshop kunt u met één druk op de knop de duurzame kenmerken van ieder product bekijken, zoals energiezuinigheid. Ook kunt u de resultaten van uw zoekopdracht vergelijken op duurzaamheidskenmerken. Door in de webshop het filter \'duurzaam\' aan te vinken bij uw zoekopdracht, worden alleen duurzame producten getoond.</p><p><strong>Persoonlijk advies</strong><br/>Heeft u vragen onze producten en diensten op het gebied van verwarming en klimaattechniek? Neem dan contact op met uw verkoopkantoor. Onze klimaatspecialisten staan voor u klaar met een professioneel advies. Zij staan in direct contact met onze leveranciers en helpen u graag bij de keuze voor het juiste product.<p>';
const assortmentTextOrange= '<p>Zoekt u kantoorbenodigdheden, een leuke premium voor uw klanten of huishoudelijke apparaten voor in uw kantine? Ook daarvoor kunt u terecht bij Technische Unie. Naast installatiematerialen leveren wij een uitgebreid assortiment consumentenartikelen.</p><p><strong>Ruime keuze consumentenartikelen</strong><br/>Van lcd-tv tot wasmachine en van inbouwapparatuur tot batterijen: Technische Unie heeft het. Ons assortiment consumentenproducten bestaat uit:</p><ul><li>Groot en klein huishoudelijke apparaten; bruin- en witgoed</li><li>Artikelen voor persoonlijke verzorging</li><li>Verwarming & luchtbehandeling</li><li>Audio- envVideoapparatuur</li><li>Kantoorbenodigdheden</li></ul><p><strong>Gedetailleerde productinformatie</strong><br/>Het complete assortiment consumentenproducten wordt overzichtelijk weergegeven op onze website. Alle producten zijn voorzien van duidelijke kleurenfoto\'s en uitgebreide productbeschrijvingen.</p><p><strong>Persoonlijk advies</strong><br/>Heeft u vragen over ons assortiment? Neem dan contact op met uw verkoopkantoor. Onze medewerkers staan voor u klaar met een professioneel advies.</p>';



export default {
  assortmentTextGreen,
  assortmentTextRed,
  assortmentTextOrange
  
}